taps:
  - homebrew/cask
  - trendyol/trendyol-tap

packages:
  - { name: awscli, state: present }
  - { name: jq, state: present }
  - { name: mas, state: present } # mas-cli(mac apple store)
  - { name: tree, state: present }
  - { name: fontconfig, state: present } # for fc-cache
  - { name: curl, state: present }
  - { name: wget, state: present }
  - { name: peco, state: present }
  - { name: zsh, state: present }
  - { name: packer, state: present }
  - { name: nmap, state: present }
  - { name: anyenv, state: present }
  - { name: docker, state: present }
  - { name: docker-compose, state: present }
  - { name: docker-shell, state: present }
  - { name: k9s, state: present }
  - { name: tmux, state: present }
  - { name: vim, state: present }
  - { name: ccat, state: present }
  - { name: exa, state: present }
